export const INITIATE_REGISTRATION = "INITIATE_REGISTRATION"
export const INITIATE_REGISTRATION_SUCCESS = "INITIATE_REGISTRATION_SUCCESS"
export const INITIATE_REGISTRATION_FAILURE = "INITIATE_REGISTRATION_FAILURE"